### PR TITLE
GSYE-369: Added control in order to start simulation based on pod memory usage

### PR DESCRIPTION
**Pull request by fabriciocarboni**
## Reason for the proposed changes

Based on [GSYE-369](https://gridsingularity.atlassian.net/browse/GSYE-369) issue while running Simulation/CN get stuck in initializing state and does not run. It happens because of pod memory usage limit is reached.

## Proposed changes
Added function to check (based of specific files) whether to start the simulation.

### CODE REVIEW

**Review by Maheen12 — APPROVED** [review]
LGTM

**Review by spyrostz — APPROVED** [review]
LGTM

**Comment by fievelk** [comment]
@fabriciocarboni is there a specific reason to use the files in `/sys`? I'm asking because one possible alternative might have been using psutils (not in the standard library, unfortunately):
```python
import psutil
psutil.virtual_memory()

# svmem(total=17179869184, available=6095384576, percent=64.5, used=9013997568, free=311848960, active=5778538496, inactive=5738041344, wired=3235459072)
```
[See docs here](https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory).

**Comment by fabriciocarboni** [comment]
Hi @fievelk Thanks for comment.

I think this code explains.
```
root@d3a-results-staging-6bcd999987-nzb2s:/app# pip3 install psutil
Collecting psutil
  Downloading psutil-5.9.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (284 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.7/284.7 kB 25.2 MB/s eta 0:00:00
Installing collected packages: psutil
Successfully installed psutil-5.9.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@d3a-results-staging-6bcd999987-nzb2s:/app# python3
Python 3.8.13 (default, Aug  2 2022, 11:41:59) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.virtual_memory().percent
38.4
>>> 
root@d3a-results-staging-6bcd999987-nzb2s:/app# cat /sys/^C
root@d3a-results-staging-6bcd999987-nzb2s:/app# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
1572864000
root@d3a-results-staging-6bcd999987-nzb2s:/app# cat /sys/fs/cgroup/memory/memory.usage_in_bytes
112336896
root@d3a-results-staging-6bcd999987-nzb2s:/app#
```

**Comment by fievelk** [comment]
@fabriciocarboni so as far as I understood, cgroups are only used by linux kernels (i.e. our Kubernetes pods).
In general, I'm usually happier to have something more generic and cross-platform, but I don't know if there's an option for it (also, this feature isn't needed for local development I suppose). If this is our only option then all good 👍 Thanks for the comment!

**Pull request merged**
