### PR TITLE
GSYE-416-refactor: Move area classes into separate modules

### PR DESCRIPTION
**Pull request by hannesdiedrich**
## Reason for the proposed changes

Please describe what we want to achieve and why.

## Proposed changes

-

**INTEGRATION_TESTS_BRANCH**=master
**GSY_FRAMEWORK_BRANCH**=master

### CODE REVIEW

**Review by mrsaemir — DISMISSED** [review]
Apart from moving things, have you done any addition/deletion to the classes? I'm asking this because the diff is so large and I couldn't review it in details.
Thanks

**Comment by hannesdiedrich** [comment]
> Apart from moving things, have you done any addition/deletion to the classes? I'm asking this because the diff is so large and I couldn't review it in details. Thanks

I only moved things around on the code side. I had to adapt the tests though. Things had to get mocked that did not have to before (Thanks Spyros, who helped me).

**Review by spyrostz — APPROVED** [review]
LGTM. I do not like that much the fact that the string "area" is repeated in the individual modules but it is tough to name it otherwise. TLDR I am good as it is

**Review by spyrostz — APPROVED** [review]
LGTM

**Review by fievelk — APPROVED** [review]

**Comment by hannesdiedrich** [comment]
> > LGTM. I do not like that much the fact that the string "area" is repeated in the individual modules but it is tough to name it otherwise. TLDR I am good as it is
> 
> @spyrostz @hannesdiedrich if you mean that the word "area" is repeated in the imports, this can be fixed by using the same strategy we've employed in `simulation/__init__.py` (importing the relevant "root" classes and using `__all__` to make them safely available).
> 
> https://github.com/gridsingularity/gsy-e/blob/8df13e08286e097e181fdbb0192f0d571554ac45/src/gsy_e/gsy_e_core/simulation/__init__.py#L15-L24

I did that:
https://github.com/gridsingularity/gsy-e/pull/1545/files#diff-5c02562bac27318ba374fac2bdc5d43cafe5cf176c7ada2a500071713d48a637R23

where do you see the area.area . Only in the test files, right? Will change it.

**Pull request merged**
